# Generated by Django 4.1 on 2022-08-25 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(1, 'Societies, registered under the Societies Registration Act, 1860 and their branches, if any, separately'), (2, 'Registered charitable trusts'), (3, 'District Rural Development Agencies, Indian Red Cross Societies and other Autonomous Bodies headed by District Collector/Chief Executive Officer/District Development Officer of Zilla Parishad'), (4, 'National/Apex Institutes including ALIMCO functioning under administrative control of the Ministry of Social Justice and Empowerment/Ministry of Health and Family Welfare'), (5, 'State Handicapped Development Corporations'), (6, 'Local Bodies- Zilla Parishad, Municipalities, District Autonomous Development Councils and Panchayats'), (7, 'Hospitals registered as separate entity, as recommended by state/central government'), (8, 'Nehru Yuvak Kendras')], max_length=128, unique=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('cin_number', models.CharField(blank=True, max_length=21, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('support_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('support_phone', models.CharField(blank=True, max_length=16, null=True)),
                ('fax_number', models.CharField(blank=True, max_length=16, null=True)),
                ('website', models.CharField(blank=True, max_length=128, null=True)),
                ('address_proof', models.FileField(upload_to='agency/address_proof')),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiaryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('udid', models.CharField(blank=True, max_length=18, null=True)),
                ('aadhaar', models.CharField(blank=True, max_length=12, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('salutation', models.CharField(blank=True, max_length=10, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('occupation', models.CharField(blank=True, max_length=256, null=True)),
                ('income', models.BigIntegerField(blank=True, null=True)),
                ('imparement', models.TextField(blank=True, null=True)),
                ('imparement_per', models.TextField(blank=True, null=True)),
                ('assistive_device', models.TextField(blank=True, null=True)),
                ('imparement_certificate', models.FileField(blank=True, null=True, upload_to='beneficiary/imparement_certificates')),
                ('income_certificate', models.FileField(blank=True, null=True, upload_to='beneficiary/income_certificates')),
                ('category_certificate', models.FileField(blank=True, null=True, upload_to='beneficiary/category_certificates')),
                ('photo', models.FileField(blank=True, null=True, upload_to='beneficiary/photos')),
            ],
        ),
        migrations.CreateModel(
            name='SchemeTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.agencydetails')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.schemetypes')),
            ],
        ),
    ]
