# Generated by Django 4.1 on 2022-08-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencydetails',
            name='country',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='agencydetails',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='agencydetails',
            name='pin_code',
            field=models.PositiveIntegerField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='agencydetails',
            name='support_designation',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='agencydetails',
            name='support_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='agencydetails',
            name='username',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
