# Generated by Django 4.1 on 2022-08-25 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_agencydetails_country_agencydetails_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiarydetails',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.agencydetails'),
        ),
        migrations.AlterField(
            model_name='agencydetails',
            name='pin_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agencydetails',
            name='type',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
        migrations.CreateModel(
            name='BenificiaryAgencyRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.agencydetails')),
                ('benificiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.beneficiarydetails')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.schemes')),
            ],
        ),
    ]
