# Generated by Django 4.1 on 2022-08-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_beneficiarydetails_agency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiarydetails',
            name='verification_status',
            field=models.CharField(blank=True, choices=[('1', 'Pending'), ('2', 'Accepted'), ('3', 'Rejected')], max_length=20, null=True),
        ),
    ]
