# Generated by Django 4.1 on 2022-08-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_beneficiarydetails_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencydetails',
            name='district',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='agencydetails',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='agencydetails',
            name='state',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiarydetails',
            name='verification_status',
            field=models.CharField(blank=True, choices=[('1', 'Pending'), ('2', 'Accepted'), ('3', 'Rejected')], default='1', max_length=20, null=True),
        ),
    ]
