# Generated by Django 4.1 on 2022-08-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_beneficiarydetails_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiarydetails',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarydetails',
            name='state',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
