# Generated by Django 4.1 on 2022-08-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_beneficiarydetails_password_beneficiarydetails_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiarydetails',
            name='district',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
